plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - benchmarking_pipelines.md
  - cheeky_peek_big_genomic_data_files.md
  - compare_dbSNP_databases.md
  - downloads_for_genomics_pipeline.md
  - grch37_vs_grch38.md
  - installation_scout.md
  - installation_vep.md
  - opentrons_programming.md
  - pipeline_files.md
  - setup-singularityContainer.md
  - setup_VCF-DART.md
  - setup_scoutContainer.md
  - setup_scoutDatabase.md
theme: jekyll-theme-cayman
